model:
  builder: "hubert"
  name: "jonatasgrosman/wav2vec2-large-xlsr-53-russian"
  collator: "wav2vec2"
  collator_params:
    augmentations:
      gain:
        enabled: true
        min_db: -10.0
        max_db: 5.0
        prob: 0.5
      time_shift:
        enabled: true
        max_shift_ratio: 0.1
        prob: 0.5

dataset:
  create_function: "golos"
  filters: []
  max_train_samples: 150000
  cache:
    use_cache: true
    cache_dir: "./data/processed_golos"
    force_recreate: false
  sources:
    golos:
      tar_path: "golos_opus.tar"
      manifests: 
        - "train/manifest.jsonl"
        - "test/crowd/manifest.jsonl"
        - "test/farfield/manifest.jsonl"
      val_fraction: 0.02
  params:
    max_duration: 30.0
    min_duration: 0.5
    sample_rate: 16000
  max_train_samples: null
  max_eval_samples: null

training:
  trainer: "Wav2Vec2Trainer"
  output_dir: "./acoustic/checkpoints_hubert"
  logging_dir: "./acoustic/checkpoints_hubert/logs"
  experiment_name: "hubert_golos"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 1.0e-5
  warmup_steps: 500
  num_train_epochs: 5
  eval_strategy: "epoch"
  save_strategy: "epoch"
  logging_strategy: "epoch"
  fp16: true
  dataloader_num_workers: 0
  load_best_model_at_end: true
  metric_for_best_model: "wer"
  greater_is_better: false
  save_total_limit: 3
  predict_with_generate: false
  resume_from: null
  metrics:
    - "wer"
    - "cer"
    - "f1"
    - "detailed_stats"
    - "ser"
    - "space_wer"
  callbacks:
    - "tqdm"
    - "eval_tqdm"